name: Maven native image build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Java ${{ matrix.java-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java-version: [11, 17]
        graalvm-version: ['22.3.1']
      fail-fast: false

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Download Liberica NIK ${{ matrix.graalvm-version }} for Java ${{ matrix.java-version }} (Linux)
        if: runner.os == 'Linux' && matrix.java-version == 17
        run: |
          download_url="https://download.bell-sw.com/vm/22.3.0/bellsoft-liberica-vm-core-openjdk17.0.5+8-22.3.0+2-linux-amd64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up Liberica NIK ${{ matrix.graalvm-version }} for Java ${{ matrix.java-version }} (Linux)
        if: runner.os == 'Linux' && matrix.java-version == 17
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: ${{ matrix.java-version }}
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          architecture: x64

      - name: Download Liberica NIK ${{ matrix.graalvm-version }} for Java ${{ matrix.java-version }} (Linux)
        if: runner.os == 'Linux' && matrix.java-version == 17
        run: |
          download_url="https://download.bell-sw.com/vm/22.3.1/bellsoft-liberica-vm-core-openjdk17.0.6+10-22.3.1+1-linux-amd64.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - name: Set up Liberica NIK ${{ matrix.graalvm-version }} for Java ${{ matrix.java-version }} (Linux)
        if: runner.os == 'Linux' && matrix.java-version == 17
        uses: actions/setup-java@v3
        with:
          distribution: jdkfile
          java-version: ${{ matrix.java-version }}
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          architecture: x64

      - name: Set up GraalVM ${{ matrix.graalvm-version }} for Java ${{ matrix.java-version }}
        if: runner.os != 'Linux' || matrix.java-version != 17
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm-version }}
          java-version: ${{ matrix.java-version }}
          components: 'native-image'

      - name: Report Java version
        run: |
          java -version
          javac -version

      - name: Install libxi-dev in Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libxi-dev

      - name: Build with Maven Wrapper (Linux)
        run: |
          cd trunk/SwingSet3
          ./mvnw -V -B package
        if: runner.os == 'Linux'

      - name: Build with Maven Wrapper (Windows)
        run: |
          cd trunk\SwingSet3
          .\mvnw.cmd -V -B package
        if: runner.os == 'Windows'

      - name: Package Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: SwingSet3 ${{ runner.os }} native image with SubstrateVM for Java ${{ matrix.java-version }}
          path: trunk/SwingSet3/target/native-image-linux/SwingSet3**

      - name: Package Windows artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: SwingSet3 ${{ runner.os }} native image with SubstrateVM for Java ${{ matrix.java-version }}
          path: trunk/SwingSet3/target/native-image-windows/

